### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by henriquemnr** [NaoDivulgue/Magento-Status-Bar-Order#3]
Pessoal, estou tentando alterar o js do módulo para se adequar a minha loja.

Consegui fazer ele ficar com a marcação correta até o pedido em transporte.

Mas não estou conseguindo.
o Código está assim: 

if(state == 'new'  && status != 'paga_ps'){
			$('#statusOrder .'+state+'').addClass("active");
			if(status == 'paga_ps'){
				$('#statusOrder .'+status+'').addClass("active");
			}else{
				$('#statusOrder .pending_payment').addClass("run");
			}
		}

		else if(state == 'complete_shipped'){
			$('#statusOrder .'+state+'').addClass("active");
		}else{
		    if(state != 'processing'){
		      $('#statusOrder .'+state+'').addClass("run");
		    }else{
		      $('#statusOrder .'+status+'').addClass("run");
		    }
		}

Queria que ele checasse pelo status complete e marcasse em verde quando esse status existisse.

**Comment by brunotda** [comment]
@henriquemnr  qual o módulo de entrega que você esta usando? 
Verifica nos status do seu magento qual o código que esta sendo usado nesta ocasião.
O status foi desenvolvido em cima do módulo do correio -pedro teixeira

**Comment by henriquemnr** [comment]
Estou usando o mesmo módulo.

Seria esses dois:

complete_shipped - quando enviado
complete -  quando entregue

Mas ele não marca em verde quando o pedido está como entregue.
Henrique Loureiro
Equipe Mão na Roda 4x4 | Escala Miniaturas
+55 11 9.8139-5281




Em seg, 1 de out de 2018 às 23:53, Bruno T. Araujo <notifications@github.com>
escreveu:

**Comment by brunotda** [comment]
Na ultima modificação que realizei ficou assim

if(state == 'new'){
    $('#statusOrder .'+state+'').addClass("active");
    	if(status == 'paga_ps' || status == 'disponivel_ps'){
		$('#statusOrder .'+status+'').addClass("active");
	}else{
		$('#statusOrder .pending_payment').addClass("run");
	}
  }else if(state == 'complete'){
   	if(status == 'complete_shipped'){
	 $('#statusOrder .'+status+'').addClass("active");
	}else{
	 $('#statusOrder .'+state+'').addClass("active");
	}
  }else{
    if(state != 'new'){
      $('#statusOrder .'+state+'').addClass("run");
    }else{
      $('#statusOrder .'+status+'').addClass("run");
    }
  }

**Comment by henriquemnr** [comment]
SHow, ficou bom agora, só tem mais um bug, quando o produto está em transporte, o entregue não fica laranja....

Segue print
![captura de tela 2018-10-02 as 00 20 35](https://user-images.githubusercontent.com/7121796/46327636-1f63a800-c5d9-11e8-92bc-6eb68684dfe3.png)

**Comment by brunotda** [comment]
**tenta deixar assim:**
}else if(state == 'complete'){
if(status == 'complete_shipped'){
      $('#statusOrder .'+status+'').addClass("run");
}

**Comment by brunotda** [comment]
Força assim:
if(status == 'complete_shipped'){
$('#statusOrder .'+status+'').addClass("active");
**$('#statusOrder .complete'').addClass("run");**
}

**Comment by henriquemnr** [comment]
Funcionou!! VLW

**Comment by brunotda** [comment]
@henriquemnr faça bom proveito do fonte .
