### ISSUE TITLE
Erro na data de criação do pedido

### ISSUE THREAD

**Issue by iurimedeiros** [NaoDivulgue/Magento-Status-Bar-Order#4]
Amigos, no meu Magento está informando a data de criação do pedido de forma incorreta, vejam na imagem em anexo, estranho também que não tenha mostrado a data do produto em transporte e produto entregue, ainda que na verdade no status este não foi entregue ainda, está despachado, mas sei que no caso ambos os status são complete [Completo], como posso fazer para a exibição funcionar direitinho? Obrigado!
![status-pedido](https://user-images.githubusercontent.com/11665895/60935003-bc591d00-a29e-11e9-9aef-3055061df2f1.JPG)

**Comment by brunotda** [comment]
@iurimedeiros Qual o formato de data/hora você utiliza? 
Os status do pedido são controlados mediante Status e State, saberia me dizer nestes dois casos que não aparecem data, qual seria o Status e State de cada um ?

Obs.: Esta melhoria foi realizada, com base no "Correios Pedro Teixeira", pode ser necessário alguma alteração, dependendo do status/state que estiver utilizando.

**Comment by iurimedeiros** [comment]
Fala @brunotda blza irmão?

Estou enviando as imagens abaixo do que está sendo exibido e do que consta em cada pedido, estou enviando também como é o atrelamento dos nossos pedidos no Magento.

Veja na imagem abaixo, ele não está puxando corretamente os horários, no caso da data de criação do pedido ele não está exibindo dentro do padrão 00/00/0000 e sim 0/0/0000, a hora está errada.
![100002729 Front](https://user-images.githubusercontent.com/11665895/60989540-a8ec9700-a31c-11e9-89d7-a86681cda747.JPG)
![100002729 Admin](https://user-images.githubusercontent.com/11665895/60989538-a8540080-a31c-11e9-8968-14483587bf85.JPG)

![100002787 Front](https://user-images.githubusercontent.com/11665895/60989542-a8ec9700-a31c-11e9-8bdc-cc7d812a944c.JPG)
![100002787 Admin](https://user-images.githubusercontent.com/11665895/60989541-a8ec9700-a31c-11e9-9e29-815c8f250656.JPG)

Veja abaixo como está o status de nossos pedidos, acredito que não seja este o problema:
![Status Pedidos](https://user-images.githubusercontent.com/11665895/60989730-0ed91e80-a31d-11e9-948f-47e1cf22344c.JPG)

Não sei se seria o caso, mas nosso PHP é versão 7.0.33: http://machinemotors.com.br/phpinfo.php

Você faz freela? Tenho algumas coisas para fazer em meu site, gostaria de pagar pelo seu serviço, aproveitando sua rápida resposta e interesse em me ajudar! (:

Abraço!

**Comment by brunotda** [comment]
@iurimedeiros de imediato o status da "entrega" é diferente do padrão "Pedro teixeira", o seu é "delivered" então onde esta: **if(status == 'complete_shipped')** altera para **if(status == 'complete_shipped' || status == 'delivered')** e adiciona a classe **"delivered"** onde houver a **class="complete_shipped".**.


Não sei como você esta tratando os pedidos "completos", mas seguindo o padrão magento esta faltando o status "complete" na lista que você encaminhou.

A hora é importante verificar o timezone do seu servidor, esta apresentando como "Default timezone America/Detroit".

Existem outros ajustes, mas é necessário entender o seu fluxo, de status/state para arrumar corretamente.

**Comment by brunotda** [comment]
Realizo freela sim,  quer que entre em contato pelo site do seu perfil? Assim evitamos a possibilidade de spam no email. 😆

**Comment by iurimedeiros** [comment]
Fala @brunotda me chama no Whats (51) 98401-4381 pra gente tratar a respeito. Obrigado! (:
